# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'AFNetworking', '~> 3.1.0'
  # Pods for TableViewDemo

end
